config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get 'open_new_post_form', action: :new_post, controller: 'jbpm'
  get 'start_jbpm', action: :start_jbpm, controller: 'jbpm'
  post 'save_new_post', action: :save_post, controller: 'jbpm'
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  
  resources :posts do
    collection do
      get 'hobby'
      get 'study'
      get 'team'
    end
end

end

app/models/post.rb
class Post < ActiveRecord::Base
	
	belongs_to :user
  	belongs_to :category
  	default_scope -> { includes(:user).order(created_at: :desc) }
  	scope :by_category, -> (branch, category_name) do 
   	 joins(:category).where(categories: {name: category_name, branch: branch}) 
 	end

  	scope :by_branch, -> (branch) do
    	joins(:category).where(categories: {branch: branch}) 
 	end

  	scope :search, -> (search) do
   	 where("title ILIKE lower(?) OR content ILIKE lower(?)", "%#{search}%", "%#{search}%")
 	end

 	validates :title, presence: true, length: { minimum: 5, maximum: 255 }
    validates :content, presence: true, length: { minimum: 20, maximum: 1000 }
    validates :category_id, presence: true
end

app/controllers/posts_controller.rb
require './app/services/posts_for_branch_service.rb'
class PostsController < ApplicationController
	before_action :redirect_if_not_signed_in, only: [:new]
	def index
  		@hobby_posts = Post.by_branch('hobby').limit(8)
        @study_posts = Post.by_branch('study').limit(8)
        @team_posts = Post.by_branch('team').limit(8)	
	end
    
    def show
  		@post = Post.find params['id']
	end

	def hobby
    	posts_for_branch(params[:action])
  	end

  	def study
    	posts_for_branch(params[:action])
  	end

  	def team
    	posts_for_branch(params[:action])
 	end

 	 def new
	    @branch = params[:branch]
	    @categories = Category.where(branch: @branch)
	    @post = Post.new
    end

	def create
	    @post = Post.new(post_params)
	    if @post.save 
	      redirect_to post_path(@post) 
	    else
	      redirect_to root_path
	    end
    end 

 	private

	def posts_for_branch(branch)
	  @categories = Category.where(branch: branch)
	  @posts = get_posts.paginate(page: params[:page])
	  respond_to do |format|
       format.html
       format.js { render partial: 'posts/posts_pagination_page' }
      end
	end

    def get_posts
    PostsForBranchService.new({
      search: params[:search],
      category: params[:category],
      branch: params[:action]
    }).call


    end

    def post_params
     params.require(:post).permit(:content, :title, :category_id)
                       .merge(user_id: current_user.id)
    end



end

app/helpers/posts_helper.rb
module PostsHelper
  def create_new_post_partial_path
    if user_signed_in?
      'posts/branch/create_new_post/signed_in'
    else
      'posts/branch/create_new_post/not_signed_in'
    end
  end

  def all_categories_button_partial_path
    if params[:category].blank?
      'posts/branch/categories/all_selected'
    else
      'posts/branch/categories/all_not_selected'
    end
  end

  def no_posts_partial_path(posts)
    posts.empty? ? 'posts/shared/no_posts' : 'shared/empty_partial'
  end

  def post_format_partial_path
    current_page?(root_path) ? 'posts/post/home_page' : 'posts/post/branch_page'
  end

   def category_field_partial_path
    if params[:category].present?
      'posts/branch/search_form/category_field'
    else
      'shared/empty_partial'
    end
  end

    def update_pagination_partial_path
	  if @posts.next_page
	    'posts/posts_pagination_page/update_pagination'
	  else
	    'posts/posts_pagination_page/remove_pagination'
	  end
	end

end

app/views/posts/_branch.html.erb
<div id="branch-main-content" class="container">
  <div class="row">
    <h1 class="page-title"><%= page_title %></h1>
    <%= render 'posts/branch/create_new_post', branch: branch %>
  </div><!-- row -->

  <div class="row">
  <%= render  'posts/branch/search_form', 
              branch: branch,
              search_placeholder: search_placeholder %>
</div><!-- row -->

  <div class="row">
    <%= render 'posts/branch/categories', branch: branch %>
  </div>

  <div class="row">
    <div class="col-sm-12" id="feed">
      <%= render @posts %>
      <%= render no_posts_partial_path @posts %>		
    </div>
  </div><!-- row -->	

  <div class="infinite-scroll">
    <%= will_paginate @posts %>
  </div>
</div><!-- container -->

app/views/posts/_modal.html.erb
<!-- Modal -->
<div  class="modal myModal" 
      tabindex="-1" 
      role="dialog" 
      aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="posted-by"></span>
        <button type="button" 
                class="close" 
                data-dismiss="modal" 
                aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
          <div class="loaded-data">
            <h3></h3>
            <p></p>
            <div class="interested"><a href="">I'm interested</a></div>
          </div><!-- loaded-data -->
        </div><!-- modal-body -->
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<%= render post_format_partial_path, post: post %>

app/views/posts/_posts_pagination_page.js.erb
$('#feed').append('<%= j render @posts %>');
<%= render update_pagination_partial_path %>

app/views/posts/hobby.html.erb
<%= render 'posts/modal' %>
<%= render partial: 'posts/branch', locals: { 
    branch: 'hobby',
    page_title: 'Find a person with the same hobby',
    search_placeholder: 'E.g. guitar playing, programming, cooking'
  } %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div id="side-menu"  class="col-sm-3">
    </div><!-- side-menu -->

    <div id="main-content" ><%= @posts[0].inspect %>
    </div><!-- main-content -->

  </div><!-- row -->
</div><!-- container -->

app/views/posts/new.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Create a new post</h1>
        <%= render 'posts/new/post_form' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div id="single-post-content" class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="posted-by">Posted by <%= @post.user.name %></div>
      <h3><%= @post.title %></h3>
      <p><%= @post.content %></p>
    </div>
    <a href=<%= start_jbpm_path(post_id: @post.id)%> ><span>Start Jbpm</span></a>
  </div><!-- row -->
</div>

app/views/posts/study.html.erb
<%= render 'posts/modal' %>
<%= render partial: 'posts/branch', locals: { 
    branch: 'study',
    page_title: 'Find a person who studies the same field as you',
    search_placeholder: 'E.g. nutrition, calculus, astrophysics'
  } %>

app/views/posts/team.html.erb
<%= render 'posts/modal' %>
<%= render partial: 'posts/branch', locals: { 
    branch: 'team',
    page_title: 'Find a person with similar interests as yours to your team',
    search_placeholder: 'E.g. musician for a band, developer for a project'
  } %>